spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.52.1:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.52.1:8848
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}-@profiles.active@.yml
  profiles:
    active: dev
